### ISSUE TITLE
下载下来编译不过

### ISSUE THREAD

**Issue by fangood** [liweijieok/ModularSample#1]
``Unable to find method 'com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by liweijieok** [comment]
你有按照这个提示去解决么？
可以尝试用他给的提示去解决。
可能跟你的本机gradle不匹配，你更换一下项目的gradle插件版本的wrapper，换成你本机的(就是下载过的以前其他项目可用的gradle插件版本)。
